{
 "title": "Validator",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Overview" } },
  {
   "title": "Latest Block Height",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{chain_id=\"iliad-0\", instance=\"10.142.0.15:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 / round(increase(cometbft_consensus_height{chain_id=\"iliad-0\", instance=\"10.142.0.15:26660\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"iliad-0\", instance=\"10.142.0.15:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{chain_id=\"iliad-0\", instance=\"10.142.0.15:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 }, "options": { "content": "# System" } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"10.142.0.15:26660\", job=\"story_validator\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"10.142.0.15:26660\", job=\"story_validator\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"10.142.0.15:26660\", job=\"story_validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"10.142.0.15:26660\", job=\"story_validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 }, "options": { "content": "# Blockchain" } },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{chain_id=\"iliad-0\", instance=\"10.142.0.15:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{instance=\"10.142.0.15:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "cometbft_consensus_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peer Trafic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(cometbft_p2p_peer_receive_bytes_total{chain_id=\"iliad-0\", instance=\"10.142.0.15:26660\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(cometbft_p2p_peer_send_bytes_total{chain_id=\"iliad-0\", instance=\"10.142.0.15:26660\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 }, "options": { "content": "# Governance" } },
  {
   "title": "Online Validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain_id=\"iliad-0\", instance=\"10.142.0.15:26660\"}-cometbft_consensus_missing_validators{chain_id=\"iliad-0\", instance=\"10.142.0.15:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting Power Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "cometbft_consensus_proposal_create_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "cometbft_consensus_proposal_receive_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting Power%",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "cometbft_consensus_round_voting_power_percent",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}